# configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@xyflow/react'

  - package-ecosystem: 'npm'
    directories:
      - '/packages/xy-shared'
      - '/sites/reactflow.dev'
      - '/sites/xyflow.com'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@xyflow/react'

  - package-ecosystem: 'npm'
    directories:
      - '/sites/svelteflow.dev'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@xyflow/svelte'
      - dependency-name: '@xyflow/react'
